image: ruby:2.6.3-alpine

pipelines:
  default:
    - step:
        caches:
          - bundler
        script:
          - RUN apk update && apk upgrade && \
               apk add --no-cache git
          - gem update --system
          - gem install bundler
          - bundle install
    - step:
        script:
          - bundle exec rubocop
          - bundle exec rspec

definitions:
  caches:
    bundler: ./vendor
