image: ruby:2.6.3-alpine

pipelines:
  default:
    - step:
        caches:
          - bundler
        script:
          - gem update --system
          - gem install bundler
          - bundle install
          - bundle exec rubocop
          - bundle exec rspec

definitions:
  caches:
    bundler: ./vendor
