version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3

    steps:
      - checkout # special step to check out source code to working directory
      - restore_cache:
          keys:
            - cron-v1-{{ checksum "Gemfile.lock" }}
            - cron-v1-
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment
      - save_cache:
          key: cron-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run Rubocop
          command: bundle exec rubocop
      - run:
          name: Run Tests
          command: bundle exec rspec
      - store_test_results:
          path: test_results
